# Generated by Django 5.2.dev20240815065219 on 2024-09-02 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityshowdown', '0002_city_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='population',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
