# Generated by Django 5.2.dev20240815065219 on 2024-09-13 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cityshowdown', '0003_city_population'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
    ]
